name: Build

on: [ workflow_dispatch ]
# push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            architecture: AMD64
            cibw_before_all: "sh build-linux.sh"
          - os: macos-11
            architecture: ARM64
            cibw_before_all: "sh build-macos-arm64.sh"
          - os: macos-11
            architecture: x86_64
            cibw_before_all: "sh build-macos.sh"

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
           CIBW_ARCH: x86_64 ARM64
        with:
           output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
