name: Build_macos_arm64

on: [ workflow_dispatch ]
#on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11 ]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
           CIBW_BEFORE_ALL: "sh build-macos-arm64.sh"
           CIBW_ARCHS_MACOS: "arm64"
   
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
