name: Build

on: [ workflow_dispatch ]
# push, pull_request]

#        os: [ ubuntu-latest, macos-latest ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
           CIBW_BEFORE_ALL_LINUX: "sh build-linux.sh"
           CIBW_BEFORE_ALL_MACOS: "sh build-macos.sh"
           CIBW_BEFORE_ALL_WINDOWS: " "
        with:
           output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
