name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-2011]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
           CIBW_BEFORE_BUILD_LINUX: "sh build-linux.sh"
           CIBW_BEFORE_BUILD_MACOS: "sh build-macos.sh"
           CIBW_BEFORE_BUILD_WINDOWS: " "

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

