name: Build

on: [ workflow_dispatch ]
# push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            architecture: AMD64
            job_name: "Ubuntu AMD64 Build"
         # - os: macos-14
         #   architecture: ARM64
         #   job_name: "MacOs ARM64 Build"
          - os: macos-14
            architecture: x86_64
            job_name: "MacOs x86_64 Build"

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
           CIBW_ARCHS_MACOS: "x86_64 arm64"
           CIBW_ARCHS_LINUX: "x86_64 aarch64"
           CIBW_BEFORE_ALL_LINUX: "sh build-linux.sh"
           CIBW_BEFORE_ALL_MACOS: "sh build-macos.sh"
           CIBW_BEFORE_ALL_WINDOWS: " "
        with:
           output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
