name: Build and Publish

on: [ workflow_dispatch ]
#on:
#  release:
#    types: [created]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            job_name: "Ubuntu AMD64 Build"
          - os: macos-14
            job_name: "MacOs 14 ARM64 Build"
          - os: macos-13
            job_name: "MacOs 13 x86_64 Build"

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
           CIBW_ARCHS_MACOS: "native"
           CIBW_ARCHS_LINUX: "x86_64"
           CIBW_BEFORE_ALL_LINUX: "sh build-linux.sh"
           CIBW_BEFORE_ALL_MACOS: "sh build-macos.sh"
           CIBW_BEFORE_ALL_WINDOWS: " "
        with:
           output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl

      - name: Install Twine
        run: python -m pip install twine

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: twine upload wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
